platform :ios, '5.0'
pod 'AFNetworking', '~> 1.2'
pod 'HawkClient', '~> 1.2.0'
pod 'FXReachability', '~> 1.1'
pod 'KNSemiModalViewController', '~> 0.3'
pod 'DLStarRating', '~> 1.1'
pod 'KIImagePager', '~> 0.0.2'
pod 'YIPopupTextView', '~> 1.0.0'
xcodeproj 'STracker/STracker.xcodeproj'